### ISSUE TITLE
navbar bg is inconsistent

### ISSUE THREAD

**Issue by kunksed** [roopakmahadane/project-commulearn#1]
When I move my mouse pointer to the nav bar, the bg seems to turn white. 

<img width="759" alt="Screenshot 2020-01-04 at 11 34 13 AM" src="https://user-images.githubusercontent.com/31513282/71760598-28cb7680-2ee6-11ea-807f-972e4faf30a0.png">

**Comment by roopakmahadane** [comment]
Fixed bg problem
